// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello/myservice.proto

package hello

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetAccResquest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccResquest) Reset()         { *m = GetAccResquest{} }
func (m *GetAccResquest) String() string { return proto.CompactTextString(m) }
func (*GetAccResquest) ProtoMessage()    {}
func (*GetAccResquest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91249fe5592e0550, []int{0}
}

func (m *GetAccResquest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccResquest.Unmarshal(m, b)
}
func (m *GetAccResquest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccResquest.Marshal(b, m, deterministic)
}
func (m *GetAccResquest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccResquest.Merge(m, src)
}
func (m *GetAccResquest) XXX_Size() int {
	return xxx_messageInfo_GetAccResquest.Size(m)
}
func (m *GetAccResquest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccResquest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccResquest proto.InternalMessageInfo

func (m *GetAccResquest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetAccResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pass                 string   `protobuf:"bytes,2,opt,name=pass,proto3" json:"pass,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccResponse) Reset()         { *m = GetAccResponse{} }
func (m *GetAccResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccResponse) ProtoMessage()    {}
func (*GetAccResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91249fe5592e0550, []int{1}
}

func (m *GetAccResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccResponse.Unmarshal(m, b)
}
func (m *GetAccResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccResponse.Marshal(b, m, deterministic)
}
func (m *GetAccResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccResponse.Merge(m, src)
}
func (m *GetAccResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccResponse.Size(m)
}
func (m *GetAccResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccResponse proto.InternalMessageInfo

func (m *GetAccResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetAccResponse) GetPass() string {
	if m != nil {
		return m.Pass
	}
	return ""
}

func (m *GetAccResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type PostResquest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pass                 string   `protobuf:"bytes,2,opt,name=pass,proto3" json:"pass,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostResquest) Reset()         { *m = PostResquest{} }
func (m *PostResquest) String() string { return proto.CompactTextString(m) }
func (*PostResquest) ProtoMessage()    {}
func (*PostResquest) Descriptor() ([]byte, []int) {
	return fileDescriptor_91249fe5592e0550, []int{2}
}

func (m *PostResquest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostResquest.Unmarshal(m, b)
}
func (m *PostResquest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostResquest.Marshal(b, m, deterministic)
}
func (m *PostResquest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostResquest.Merge(m, src)
}
func (m *PostResquest) XXX_Size() int {
	return xxx_messageInfo_PostResquest.Size(m)
}
func (m *PostResquest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostResquest.DiscardUnknown(m)
}

var xxx_messageInfo_PostResquest proto.InternalMessageInfo

func (m *PostResquest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PostResquest) GetPass() string {
	if m != nil {
		return m.Pass
	}
	return ""
}

func (m *PostResquest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type PostResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostResponse) Reset()         { *m = PostResponse{} }
func (m *PostResponse) String() string { return proto.CompactTextString(m) }
func (*PostResponse) ProtoMessage()    {}
func (*PostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_91249fe5592e0550, []int{3}
}

func (m *PostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostResponse.Unmarshal(m, b)
}
func (m *PostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostResponse.Marshal(b, m, deterministic)
}
func (m *PostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostResponse.Merge(m, src)
}
func (m *PostResponse) XXX_Size() int {
	return xxx_messageInfo_PostResponse.Size(m)
}
func (m *PostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostResponse proto.InternalMessageInfo

func (m *PostResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAccResquest)(nil), "hello.GetAccResquest")
	proto.RegisterType((*GetAccResponse)(nil), "hello.GetAccResponse")
	proto.RegisterType((*PostResquest)(nil), "hello.PostResquest")
	proto.RegisterType((*PostResponse)(nil), "hello.PostResponse")
}

func init() { proto.RegisterFile("hello/myservice.proto", fileDescriptor_91249fe5592e0550) }

var fileDescriptor_91249fe5592e0550 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0x48, 0xcd, 0xc9,
	0xc9, 0xd7, 0xcf, 0xad, 0x2c, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x05, 0x0b, 0x4b, 0xc9, 0xa4, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x27, 0x16,
	0x64, 0xea, 0x27, 0xe6, 0xe5, 0xe5, 0x97, 0x24, 0x96, 0x64, 0xe6, 0xe7, 0x15, 0x43, 0x14, 0x29,
	0x29, 0x70, 0xf1, 0xb9, 0xa7, 0x96, 0x38, 0x26, 0x27, 0x07, 0xa5, 0x16, 0x17, 0x96, 0xa6, 0x16,
	0x97, 0x08, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x31, 0x65,
	0xa6, 0x28, 0xf9, 0x21, 0xa9, 0x28, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x12, 0xe2, 0x62, 0xc9, 0x4b,
	0xcc, 0x4d, 0x85, 0xaa, 0x01, 0xb3, 0x41, 0x62, 0x05, 0x89, 0xc5, 0xc5, 0x12, 0x4c, 0x10, 0x31,
	0x10, 0x5b, 0x48, 0x84, 0x8b, 0xb5, 0x20, 0x23, 0x3f, 0x2f, 0x55, 0x82, 0x19, 0x2c, 0x08, 0xe1,
	0x28, 0xf9, 0x70, 0xf1, 0x04, 0xe4, 0x17, 0x97, 0xc0, 0xed, 0xa3, 0xcc, 0x34, 0x39, 0xb8, 0x69,
	0x10, 0xb7, 0xa1, 0xb9, 0xde, 0x68, 0x16, 0x23, 0x17, 0x8f, 0x07, 0x28, 0x1c, 0x82, 0x21, 0x61,
	0x23, 0xe4, 0xc6, 0xc5, 0xec, 0x9e, 0x5a, 0x22, 0x24, 0xaa, 0x07, 0x0e, 0x1d, 0x3d, 0x54, 0xcf,
	0x4b, 0x61, 0x08, 0x83, 0x4d, 0x55, 0x12, 0x6c, 0xba, 0xfc, 0x64, 0x32, 0x13, 0xb7, 0x10, 0xa7,
	0x7e, 0x7a, 0x6a, 0x89, 0x7e, 0x75, 0x66, 0x4a, 0xad, 0x90, 0x13, 0x17, 0x0b, 0xc8, 0x62, 0x21,
	0x61, 0xa8, 0x0e, 0x64, 0x3f, 0x49, 0xa1, 0x09, 0x42, 0x0c, 0x11, 0x00, 0x1b, 0xc2, 0xa5, 0xc4,
	0xaa, 0x5f, 0x90, 0x5f, 0x5c, 0x62, 0xc5, 0xa8, 0xe5, 0xc4, 0x1e, 0x05, 0x89, 0xa3, 0x24, 0x36,
	0x70, 0x64, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x63, 0xcf, 0xb6, 0xca, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloServiceClient is the client API for HelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloServiceClient interface {
	Get(ctx context.Context, in *GetAccResquest, opts ...grpc.CallOption) (*GetAccResponse, error)
	Post(ctx context.Context, in *PostResquest, opts ...grpc.CallOption) (*PostResponse, error)
}

type helloServiceClient struct {
	cc *grpc.ClientConn
}

func NewHelloServiceClient(cc *grpc.ClientConn) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) Get(ctx context.Context, in *GetAccResquest, opts ...grpc.CallOption) (*GetAccResponse, error) {
	out := new(GetAccResponse)
	err := c.cc.Invoke(ctx, "/hello.HelloService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloServiceClient) Post(ctx context.Context, in *PostResquest, opts ...grpc.CallOption) (*PostResponse, error) {
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, "/hello.HelloService/Post", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServiceServer is the server API for HelloService service.
type HelloServiceServer interface {
	Get(context.Context, *GetAccResquest) (*GetAccResponse, error)
	Post(context.Context, *PostResquest) (*PostResponse, error)
}

// UnimplementedHelloServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServiceServer struct {
}

func (*UnimplementedHelloServiceServer) Get(ctx context.Context, req *GetAccResquest) (*GetAccResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedHelloServiceServer) Post(ctx context.Context, req *PostResquest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Post not implemented")
}

func RegisterHelloServiceServer(s *grpc.Server, srv HelloServiceServer) {
	s.RegisterService(&_HelloService_serviceDesc, srv)
}

func _HelloService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccResquest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.HelloService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).Get(ctx, req.(*GetAccResquest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloService_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostResquest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.HelloService/Post",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).Post(ctx, req.(*PostResquest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hello.HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _HelloService_Get_Handler,
		},
		{
			MethodName: "Post",
			Handler:    _HelloService_Post_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello/myservice.proto",
}
